### ISSUE TITLE
Show some sample programs

### ISSUE THREAD

**Issue by tosa-no-onchan** [torque/qrdec#1]
Hi,torque.
Would you show some sample programs?
I would like to use this qr decode program from my qr-code decode c++ application.

**Comment by tosa-no-onchan** [comment]
I found main() in reader.c
Thanks!

**Comment by torque** [comment]
It would probably make sense to move `reader.c` and `image.c` out of the source folder, since they are not part of the QR decoding library itself.

The only other real example code I have is https://github.com/torque/deqr/blob/master/deqr/qrdec.pyx#L160-L197 which is not any more sophisticated than `reader.c` and has the disadvantage of being written in Cython.

**Comment by torque** [comment]
5af108474c5dc2bd5b74b5da97b2d0b9874c1fc9
